persistence:
  enabled: true
  storageClass: "###ZARF_STORAGE_CLASS###"
  size: 20Gi
image:
  repository: "###ZARF_REGISTRY###/library/registry"
secrets:
  htpasswd: "###ZARF_HTPASSWD###"
  configData:
    http:
      secret: "###ZARF_REGISTRY_SECRET###"

# https://github.com/containerd/containerd/blob/v1.5.8/pkg/cri/server/image_pull.go#L412
# thx containerd *magic* :-D
# tlsSecretName: tls-pem
service:
  type: NodePort
  nodePort: "###ZARF_NODEPORT###"
resources:
  requests:
    cpu: "500m"
    memory: "256Mi"
  limits:
    cpu: "3"
    memory: "2Gi"